export enum UserRole {
  APPLICANT = 'APPLICANT',
  CONSULTANT = 'CONSULTANT',
  ADMIN = 'ADMIN',
}

export enum GoalType {
  STUDY = 'STUDY',
  AUSBILDUNG = 'AUSBILDUNG',
  EMPLOYMENT = 'EMPLOYMENT',
}

export enum DocumentType {
  CV = 'CV',
  DEGREE = 'DEGREE',
  TRANSCRIPT = 'TRANSCRIPT',
  CERTIFICATE = 'CERTIFICATE',
  EXPERIENCE_LETTER = 'EXPERIENCE_LETTER',
  LANGUAGE_CERTIFICATE = 'LANGUAGE_CERTIFICATE',
  PROFESSIONAL_CERTIFICATE = 'PROFESSIONAL_CERTIFICATE',
  OTHER = 'OTHER',
}

export enum DocumentStatus {
  UPLOADING = 'UPLOADING',
  UPLOADED = 'UPLOADED',
  PROCESSING = 'PROCESSING',
  EXTRACTING = 'EXTRACTING',
  CHECKING = 'CHECKING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REQUIRES_REVIEW = 'REQUIRES_REVIEW',
}

export enum VerificationStatus {
  UNVERIFIED = 'UNVERIFIED',
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum SourceType {
  APPLICANT_PROVIDED = 'APPLICANT_PROVIDED',
  DOCUMENT_EXTRACTED = 'DOCUMENT_EXTRACTED',
  VIDEO_EXTRACTED = 'VIDEO_EXTRACTED',
  AI_GENERATED = 'AI_GENERATED',
  CONSULTANT_VERIFIED = 'CONSULTANT_VERIFIED',
}

export enum QualificationStatus {
  QUALIFIED = 'QUALIFIED',
  PARTIALLY_QUALIFIED = 'PARTIALLY_QUALIFIED',
  MORE_INFORMATION_REQUIRED = 'MORE_INFORMATION_REQUIRED',
  NOT_CURRENTLY_QUALIFIED = 'NOT_CURRENTLY_QUALIFIED',
}

export enum OpportunityType {
  STUDY = 'STUDY',
  AUSBILDUNG = 'AUSBILDUNG',
  EMPLOYMENT = 'EMPLOYMENT',
}

export enum RecommendationType {
  EDUCARO_SERVICE = 'EDUCARO_SERVICE',
  CONSULTANT_REFERRAL = 'CONSULTANT_REFERRAL',
  APPLICANT_ACTION = 'APPLICANT_ACTION',
}

export enum RecommendationStatus {
  ACTIVE = 'ACTIVE',
  ACCEPTED = 'ACCEPTED',
  DISMISSED = 'DISMISSED',
  SUPERSEDED = 'SUPERSEDED',
}

export enum JourneyStepStatus {
  LOCKED = 'LOCKED',
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  REQUIRES_REVIEW = 'REQUIRES_REVIEW',
}

export enum AgentExecutionStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REQUIRES_REVIEW = 'REQUIRES_REVIEW',
}

export enum ReviewStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CLARIFICATION_REQUESTED = 'CLARIFICATION_REQUESTED',
}

export enum ApplicationStatus {
  DRAFT = 'DRAFT',
  READY_FOR_REVIEW = 'READY_FOR_REVIEW',
  CONFIRMED = 'CONFIRMED',
  SUBMITTED = 'SUBMITTED',
  INTERVIEW_INVITED = 'INTERVIEW_INVITED',
  INTERVIEW_COMPLETED = 'INTERVIEW_COMPLETED',
  TECHNICAL_ROUND = 'TECHNICAL_ROUND',
  FINAL_REVIEW = 'FINAL_REVIEW',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  WITHDRAWN = 'WITHDRAWN',
}

export enum InterviewRoomStatus {
  WAITING = 'WAITING',
  SCHEDULED = 'SCHEDULED',
  LIVE = 'LIVE',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum InterviewParticipantRole {
  APPLICANT = 'APPLICANT',
  INTERVIEWER = 'INTERVIEWER',
  PANELIST = 'PANELIST',
}

export enum InvitationStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  RESCHEDULE_REQUESTED = 'RESCHEDULE_REQUESTED',
  DECLINED = 'DECLINED',
  EXPIRED = 'EXPIRED',
}

export enum EvaluationRecommendation {
  ADVANCE = 'ADVANCE',
  HUMAN_REVIEW = 'HUMAN_REVIEW',
  DO_NOT_ADVANCE = 'DO_NOT_ADVANCE',
}
